### PR TITLE
Add support for complex initializers

### LINKED ISSUE #3: Non-pure initializers should generate __postset
Is there a way to generate __postset (complex initializers) in the output library using this? Trying to initialize some global singletons (like `TextEncoder`) for later reuse.

For now I'm doing `utf8Decoder || (utf8Decoder = new TextDecoder());` in functions that need them, but would prefer to move initialization to corresponding section.

### PR DESCRIPTION
**Pull request by RReverser**
- Initializes variables to undefined (`void 0`) and not `null` by default to match with pure JavaScript behavior.
 - Generates `__postset` declaration for impure initializers and `__deps` with any variables required for the delayed initialization.

Example:

**Input:**

```js
export var x = getAnswer() + 10;
var answer = 42;

function getAnswer() {
	return answer;
}
```

**Output:**

```js
Object.assign(LibraryManager.library, {
    x: void 0,
    x__postset: 'x = __myLib_getAnswer() + 10;',
    _myLib_answer: 42,
    _myLib_getAnswer: function () {
        return __myLib_answer;
    },
    _myLib_getAnswer__deps: ['_myLib_answer'],
    x__deps: ['_myLib_getAnswer']
});
```

Fixes #3.

### CODE REVIEW

**Comment by RReverser** [comment]
One downside is that, unlike in pure JS, there will be no temporary `undefined` value for regular `var`s, meaning this:

```
var y = x;
var x = 42;
```

Will still work in the generated code, but if one uses `let` or `const`, this wouldn't work in pure JS either due to TDZ.

Not sure if I should add a check to disallow impure `var`s or maybe `var`s completely, or should just not care about it for now...

**Comment by RReverser** [comment]
Update: also fixed #4.

**Comment by RReverser** [comment]
And #2.

**Comment by RReverser** [comment]
@chpio Thanks for adding me! Does this mean I should merge myself when ready or..?

**Comment by chpio** [comment]
> @chpio Thanks for adding me! Does this mean I should merge myself when ready or..?

yeah :)

**Comment by RReverser** [comment]
Merging for now, will continue work directly on `develop` branch here.

**Comment by RReverser** [comment]
@chpio Any chance you could bump version & release what we have now?

**Comment by chpio** [comment]
removed the `develop` branch, no need for git flow complexity in a toy project.


Do you think a ~patch~ minor version bump (0.1.1) will be enough for this?

**Comment by RReverser** [comment]
Hmm... I *hope* I haven't broken anything with all these changes back then, but maybe 0.2.0 would be a safer bet.

**Comment by chpio** [comment]
done, i also updated rollup.

**Pull request merged**
